language: python

python: 
  - '3.6'

jobs:
  include:
    - stage: Linting Test
      install: "pip install -r requirements.txt"
      script: flake8 falcon/

    - stage: Unit Test
      sudo: required
      services: docker
      script: cd falcon/test && bash test.sh
