jobs:
  include:
    - stage: Linting Test
      language: python
      python: 
      - '3.6'
      install: "pip install -r requirements.txt"
      script: flake8 falcon/

    - stage: Unit Test
      language: python
      python:
      - '3.6'
      sudo: required
      services: docker
      script: cd falcon/test && bash test.sh
