language: python

python: 
  - '3.6'

install: "pip install -r requirements.txt"

jobs:
  include:
    # The linting test is fast and cheap so run it first
    - stage: Linting Test
      script: 
        # Check Black code style compliance
        - black falcon/ --skip-string-normalization --check
        # Check PEP-8 compliance
        - flake8 falcon/

    # The unit test is a bit more expensive so run it only
    # if the linting test passes
    - stage: Unit Test
      sudo: required
      services: docker
      script: cd falcon/test && bash test.sh
